# Generated by Django 4.1.7 on 2023-03-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_coffee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chai', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
